#!/bin/bash
directory=$1

echo [Initiating]
if [ "$directory" == '.' ]; then directory_name=${PWD##*/}; else directory_name=$(basename "$directory"); fi

atom $directory &
tm -t $directory_name -d $directory
